name: Pull Request

on: pull_request

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v1        

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          7.0.x
          
    - name: Build & Test
      run: dotnet test EnglishTrainer.sln --configuration Release /warnaserror
